name: Compare

on: [push, pull_request]

jobs:
  gerbers:
    name: Plot gerbers
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki7

    steps:
    - uses: actions/checkout@v3

    - name: Run KiBot
      run: | 
        kibot -c ./gerbers.kibot.yaml

    - name: Upload Gerber files
      uses: actions/upload-artifact@v3
      with: 
        name: Gerbers
        path: ./gerbers/

  drawings:
    name: Plot drawings
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki7

    steps:
    - uses: actions/checkout@v3

    - name: Run KiBot
      run: | 
        kibot -c ./drawings.kibot.yaml

    - name: Upload Gerber files
      uses: actions/upload-artifact@v3
      with: 
        name: Drawings
        path: ./drawings/

  compare:
    name: Compare to desired output
    runs-on: ubuntu-latest
    needs: drawings

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: Drawings
        path: .

    - name: Compare ours against a photo
      run: | 
        compare -metric PSNR ./front-drawn.png ./photo/front.jpg front_difference.png
  
    - name: Upload Report
      uses: actions/upload-artifact@v3
      with: 
        name: Similiarity
        path: |
         ./front-render.png